#!/bin/bash

ENV=v96

function get-deps()
{
    local MODULE=$1

    if [ ! -f $MODULE.deps ]; then
        VER=$(scbi --env=$ENV --module-version $MODULE)
        echo $MODULE:$VER

        echo salome: $MODULE:$VER > $MODULE.deps

        scbi --env=$ENV --list-depends:direct $MODULE |
            while read m; do
                echo "salome: $m"
            done >> $MODULE.deps

        while read p m; do
            mm=$(echo $m | cut -d':' -f1)
            get-deps $mm
        done < $MODULE.deps

        scbi --env=$ENV --list-depends:direct --list-externals:only $MODULE |
            while read m; do
                echo "external: $m"
            done >> $MODULE.deps
    fi
}

rm -fr .deps && mkdir .deps && cd .deps
[ $? == 1 ] && exit 1

get-deps salome
