#! /bin/bash

SALOME_ROOT=$(cd $(dirname ${BASH_SOURCE[0]});pwd)
XMLFILE=$SALOME_ROOT/CatalogResources.xml
VERSION="<salome_version>"

declare -A SERVER=(["gaia"]="/projets/salome/logiciels/salome/$VERSION"
                   ["cronos"]="/software/rd/salome/logiciels/salome/$VERSION")

declare -A USERHOME=(["gaia"]="/scratch/$USER"
                     ["cronos"]="/scratch/users/$USER")

function addToCatalog()
{
    local xml=$1
    local name=$2
    local hostname=$3
    local appliPath=$4
    local workingDirectory=$5

    local Catalog

    case $name in
        localhost)
            local nbn=$(LANG=C lscpu | grep '^CPU(' | cut -d':' -f2 | tr -d ' ')
            declare -A Catalog=(["name"]=\"$name\"
                                ["hostname"]=\"$name\"
                                ["nbOfNodes"]=\"$nbn\")
            ;;
        *)
            declare -A Catalog=(["name"]=\"$name\"
                                ["hostname"]=\"$hostname\"
                                ["appliPath"]=\"$appliPath\"
                                ["workingDirectory"]=\"$workingDirectory\"
                                ["type"]=\""cluster"\"
                                ["protocol"]=\""ssh"\"
                                ["iprotocol"]=\""srun"\"
                                ["canLaunchBatchJobs"]=\""true"\"
                                ["canRunContainers"]=\""false"\"
                                ["batch"]=\""slurm"\"
                                ["mpi"]=\""no mpi"\"
                                ["userName"]=\""$USER"\")
            ;;
    esac

    {
        echo -n "<machine"
        for att in ${!Catalog[@]}; do
            echo -n " $att=${Catalog[$att]}"
        done
        echo "/>"
    } >> $xml
}

function _error_msg()
{
    local NAME=$1

    echo "CREATE_CATALOG - WARNING - $NAME configuration failed!"
    echo "Check the salome installation on $NAME.hpc.edf.fr"
    echo "Verify your access rights to $name.hpc.edf.fr and try again."
    echo "SALOME cannot be installed in ${USERHOME[$NAME]}"
}

echo "<resources>" > $XMLFILE

for name in ${!SERVER[@]}; do
    VIRTUAL_APPLI="${USERHOME[$name]}/$VERSION"
    ORIG_APPLI="${SERVER[$name]}/"

    #  On CRONOS we need to check if the user has access to /rd/ or /restricted/
    #  In this case we set ORIG_APPLI to point to the right location.

    if [[ "$name" == "cronos" ]]; then
        # Test repository access and update remote appli dir if necessary
        connect_cronos=$(ssh -o StrictHostKeyChecking=no $USER@$name.hpc.edf.fr "bash -c 'ls $ORIG_APPLI && echo OK'")

        if [[ "$connect_cronos" =~ ^ls: ]]; then
            ORIG_APPLI=/software/restricted/salome/logiciels/salome/
            connect_cronos=$(ssh -o StrictHostKeyChecking=no $USER@$name.hpc.edf.fr "bash -c 'ls $ORIG_APPLI && echo OK'")
            if [[ "$connect_cronos" =~ ^ls: ]]; then
                echo "Vous n'avez pas les droits suffisants sur Cronos pour installer salome."
		_error_msg $name
		continue
            else
                sed -i "s,software/rd,software/restricted,g" servers.pvsc
            fi
        fi
    fi

    if [[ "$name" == "cronos" ]]; then
        ssh -o StrictHostKeyChecking=no $USER@$name.hpc.edf.fr \
            "mkdir -p $VIRTUAL_APPLI && \
             rm -rf $VIRTUAL_APPLI/* && \
             ln -sr $ORIG_APPLI/salome $VIRTUAL_APPLI/salome" >/dev/null 2>&1
    elif [[ "$name" == "gaia" ]]; then
        python3 create_exec.py $VERSION
        chmod +x salome_remote_launcher
        ssh -o StrictHostKeyChecking=no $USER@$name.hpc.edf.fr \
            "mkdir -p $VIRTUAL_APPLI && \
             rm -rf $VIRTUAL_APPLI/*" >/dev/null 2>&1
        scp salome_remote_launcher $USER@$name.hpc.edf.fr:$VIRTUAL_APPLI/salome
        rm salome_remote_launcher
    fi

    if [[ $? != 0 ]]; then
	_error_msg $name
        continue
    fi

    ssh -o StrictHostKeyChecking=no $USER@$name.hpc.edf.fr \
        "[[ -e $VIRTUAL_APPLI/salome ]]" >/dev/null 2>&1

    if [[ $? = 0 ]]; then
        addToCatalog $XMLFILE "$name" "$name.hpc.edf.fr" \
                     "$VIRTUAL_APPLI/salome" "${USERHOME[$name]}/workingdir"
    else
	_error_msg $name
        continue
    fi
done

addToCatalog $XMLFILE "localhost"
echo "</resources>" >> $XMLFILE

#  Get SALOME env to have KERNEL_ROOT_DIR

source env_launch.sh

[[ -d $KERNEL_ROOT_DIR/share/salome/resources/kernel ]] &&
    cp $XMLFILE $KERNEL_ROOT_DIR/share/salome/resources/kernel
