#! /bin/bash

function usage()
{
cat<<EOF
usage: $0 <version> <salome_install_dir>

This script allow us to install Meshgems

Options:
 -h    Show this message
EOF
}

while getopts ":h" OPTION
do
  case $OPTION in
    h)
      usage
      exit 1
      ;;
  esac
done

MGVERSION=$1
SALOME_INSTALL_DIR=$2

if [[ -z "$MGVERSION" ]]; then
    echo MeshGems version was not defined
    usage
    exit 1
fi

if [[ -z "$SALOME_INSTALL_DIR" ]]; then
    echo SALOME_INSTALL_DIR was not defined;
    echo We assign it to the link where this file is stored
    SALOME_INSTALL_DIR=$(cd $(dirname ${BASH_SOURCE[0]});pwd)
    echo
fi

MG_ARCHIVE=meshgems-edfbin-$MGVERSION.tar.gz
MINIO_URL=https://minio.retd.edf.fr/salome/Releases/MeshGems
MG_ARCHIVE_URL=$MINIO_URL/$MG_ARCHIVE

EDFMODULE_INSTALL_DIR=$SALOME_INSTALL_DIR/EDF
MG_INSTALL_DIR=$EDFMODULE_INSTALL_DIR/s-meshgems

# install mg archive

wget -q $MG_ARCHIVE_URL
if [[ $? -ne 0 ]]; then
    echo "File Meshgems archive with version $MGVERSION seems to be missing on $MINIO_URL.."
    echo "Please check or contact tma.edf@opencascade.com ."
    exit 1
fi

rm -rf $MG_INSTALL_DIR
tar xf $MG_ARCHIVE -C $EDFMODULE_INSTALL_DIR
mv $MG_INSTALL_DIR/99_s_meshgems.* $SALOME_INSTALL_DIR/extra.env.d/
