#!/bin/bash

source $(dirname ${BASH_SOURCE[0]})/install-setup-common

AUTO=0

while [ ! -z $1 ]; do
    case "$1" in
        --auto)
            AUTO=1;
            break;
            ;;
        *)
            ;;
    esac
    shift;
done

# check for python3
#
BINDIR=$(basename $(ls -1d BINARIES-*))

if [[ $DISTRIBUTION_ID -eq "Debian" && $OS_VERSION -eq "9" ]]; then
    echo Python is embedded into salome on debian9
elif [[ "$(lsb_release -d)" =~ "Red Hat" ]]; then
    echo Python is embedded into salome on Red Hat
else
    if [ -z "$(python --version 2>&1 | grep ' 3\.')" ]; then
        echo Python2 is default, checking for python3

        if [ -f /usr/bin/python3 ]; then
            echo Found Python3 in /usr/bin/python3, setup links
            ln -s /usr/bin/python3 $BINDIR/SALOME/bin/salome/python
        else
            echo Cannot found a Python3 installation.
            echo SALOME will not work properly.
        fi
    fi
fi

echo Installing SALOME

# In AUTO mode we install in $PWD otherwise the install directory
# is asked to user.
prefix=$PWD

SUDO=""

if [[ $AUTO == 0 ]]; then
    prefix=$(get-install-directory \$HOME/opt/salome)

    check-writable $prefix || SUDO=sudo

    $SUDO mkdir -p $prefix
    $SUDO mv * .[a-z]* $prefix/
fi

template-conversion $prefix $DISTRIBUTION_ID $OS_VERSION

if [[ $AUTO == 0 ]]; then
    $SUDO rm -f $prefix/setup

    $SUDO chown $USER -R $prefix
fi

echo "SALOME installation terminated, to start:"
echo "$ $prefix/salome"
