#!/bin/bash

source $(dirname ${BASH_SOURCE[0]})/install-setup-common

AUTO=0

while [ ! -z $1 ]; do
    case "$1" in
        --auto)
            AUTO=1;
            break;
            ;;
        *)
            ;;
    esac
    shift;
done

#  Check for python3

check-for-python3

echo Installing SALOME

# In AUTO mode we install in $PWD otherwise the install directory
# is asked to user.
prefix=$PWD

SUDO=""

if [[ $AUTO == 0 ]]; then
    prefix=$(get-install-directory \$HOME/opt/salome)

    check-writable $prefix || SUDO=sudo

    $SUDO mkdir -p $prefix
    $SUDO mv * .[a-z]* $prefix/
fi

template-conversion $prefix $DISTRIBUTION_ID $OS_VERSION

if [[ $AUTO == 0 ]]; then
    $SUDO rm -f $prefix/setup

    $SUDO chown $USER -R $prefix
fi

echo "SALOME installation terminated, to start:"
echo "$ $prefix/salome"
